### ISSUE TITLE
[BUG] CI is failing

### ISSUE THREAD

**Issue by jinmayamashita** [monstar-lab-oss/ml-frontend#1202]
## Describe the bug

CI is failing. It seems like the failure is due to the missing 'pnpm version' configuration.

## To Reproduce

```
Run pnpm/action-setup@v2
Running self-installer...
  Error: No pnpm version is specified.
  Please specify it by one of the following ways:
    - in the GitHub Action config with the key "version"
    - in the package.json with the key "packageManager"
      at readTarget (/home/runner/work/_actions/pnpm/action-setup/v2/dist/index.js:1:3939)
      at async runSelfInstaller (/home/runner/work/_actions/pnpm/action-setup/v2/dist/index.js:1:292[8](https://github.com/monstar-lab-oss/ml-frontend/actions/runs/7335808539/job/19974218905#step:3:9))
      at async install (/home/runner/work/_actions/pnpm/action-setup/v2/dist/index.js:1:2239)
      at async main (/home/runner/work/_actions/pnpm/action-setup/v2/dist/index.js:1:445)
  Error: Error: No pnpm version is specified.
  Please specify it by one of the following ways:
    - in the GitHub Action config with the key "version"
    - in the package.json with the key "packageManager"
```

https://github.com/monstar-lab-oss/ml-frontend/actions/runs/7335808539/job/19974218905

## Expected behavior

The CI has passed, and we can proceed with the release.

## Related packages/templates
`start-frontend`

## Screenshots (optional)
N/A
## Additional context (optional)
N/A

**Comment by ptrkdan** [comment]
The release failed due to a missing `release` command, so I'm reopening this issue.
It looks like we need to add a `release` script, similar to the one below:
```json
{
  "scripts": {
    // Include build, lint, test - all the things you need to run
    // before publishing
    "publish-packages": "turbo run build lint test && changeset version && changeset publish"
  }
}
```


Reference: https://turbo.build/repo/docs/handbook/publishing-packages/versioning-and-publishing#using-changesets-with-turborepo
